nombre = input('Ingresar Nombre: ')
apellido = input('Ingresar Apellido: ')
seccion = input('Ingresar Código-sección: ')
sede = input('Ingresar Sede: ')
print ()
print ("Datos ingresados:")
print ("-Nombre y Apellido:",nombre,apellido)
print ("-Código-sección:",seccion)
print ("-Sede:",sede)
